### ISSUE TITLE
PHP Warning if words include special characters

### ISSUE THREAD

**Issue by louderthan10** [sjelfull/Craft-Lettering#1]
Hi @sjelfull. Love that you made this!

I just ran into an error that seems to occur when the text being filtered contains a special character, like an ampersand I haven't tested with other characters yet).

I'm using the filter on a title tag with lettering('words') mode. Note, I also use a smartypants filter on the same tag… but get the same error whether or not the smartypants filter is applied.

Error attached:

<img width="1509" alt="screen shot 2016-05-15 at 22 56 01" src="https://cloud.githubusercontent.com/assets/49751/15281478/76410bc2-1af0-11e6-841e-6f13cf2b9352.png">

[lettering-trace.txt](https://github.com/sjelfull/Craft-Lettering/files/265628/lettering-trace.txt)

Any ideas?

Thanks!

**Comment by sjelfull** [comment]
Hey Travis, I got bit by this too on a project i'm currently working on. Not sure what to do about this yet, but I'll get back to you with a fix as soon as I have one.

Let me know if you come up with something before I do.

**Comment by louderthan10** [comment]
Sounds great! I'll let you know.

Not sure if this is what happening, but would it make a difference if this plugin didn't escape special characters at all? It might be nice to give that responsibility to a different filter anyway (like typogrify). (I'm no plugin/PHP developer so I could be way out to lunch).

**Comment by sjelfull** [comment]
@louderthan10 I found this. Seems like ignoring the warnings works well.

http://stackoverflow.com/questions/12328322/php-domdocumentloadhtml-domdocument-loadhtml-htmlparseentityref-no-name
